name: Lint Code (Eslint)

on: push

defaults:
  run:
    working-directory: ./

jobs:
  code-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci

      - name: Run dependency analysis
        uses: ./
